# Generated by Django 4.1.4 on 2022-12-19 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название')),
                ('date', models.DateTimeField(verbose_name='Дедлайн')),
                ('task', models.TextField(verbose_name='Описание')),
                ('is_complete', models.BooleanField(default=False, verbose_name='Задание выполнено')),
                ('is_moder', models.BooleanField(default=False, verbose_name='Задание отправлено на проверку')),
            ],
        ),
    ]
